name = "Simple Search"
author = "manuelcontrera"
version = "1.0.0"
description = "Presiona ESPACIO para enfocar la barra de URL y escribir % en Zen Browser."

[zen]
min_version = "1.0"

[install]
type = "extension"
source = "manifest.json"
files = ["mod.js"]

[info]
license = "MIT"
repository = "https://github.com/manuelcontrera/Simple-Search-Zen"
